// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQOxOC7I63rAOkM_kB75aqH2sOlyYa0NM',
    appId: '1:597748077212:web:fdc303a70722955ec25359',
    messagingSenderId: '597748077212',
    projectId: 'abril-34b9c',
    authDomain: 'abril-34b9c.firebaseapp.com',
    storageBucket: 'abril-34b9c.firebasestorage.app',
    measurementId: 'G-6BDET279B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsGSd5N5N5u0hSW59-0CLqzYeHHCLCGao',
    appId: '1:597748077212:android:04a38c12116f8ee8c25359',
    messagingSenderId: '597748077212',
    projectId: 'abril-34b9c',
    storageBucket: 'abril-34b9c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXZv8HcJdKzAm9Q0ymdLi94KuH9V35OWI',
    appId: '1:597748077212:ios:23731cf843cc6516c25359',
    messagingSenderId: '597748077212',
    projectId: 'abril-34b9c',
    storageBucket: 'abril-34b9c.firebasestorage.app',
    iosBundleId: 'com.labstock.appClinica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQOxOC7I63rAOkM_kB75aqH2sOlyYa0NM',
    appId: '1:597748077212:web:946eeed39f28d228c25359',
    messagingSenderId: '597748077212',
    projectId: 'abril-34b9c',
    authDomain: 'abril-34b9c.firebaseapp.com',
    storageBucket: 'abril-34b9c.firebasestorage.app',
    measurementId: 'G-8PHF4MMN83',
  );
}
