name: CI - Integración Continua LoginApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flutter-ci:
    name: Flutter Analyze & Test
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Descargar dependencias
        run: flutter pub get

      - name: Analizar código Flutter
        run: flutter analyze --no-fatal-infos

      - name: Ejecutar pruebas unitarias y de widgets
        run: flutter test --reporter expanded

      - name: Confirmar estado exitoso
        if: success()
        run: echo "Todas las pruebas de Flutter y el análisis estático pasaron exitosamente."
